### ISSUE TITLE
error TS2304: Cannot find name 'MyItemOptionProps1' occurs when building code on renoV syntax for angular

### ISSUE THREAD

**Issue by IgnatovDan** [DevExpress/devextreme-renovation#724]
The error occurs after I started the 'npm run build:angular' command for some configuration of 'nested' props with inheritance:
```
@ComponentBindings()
export class MycomponentProps extends BaseWidgetProps {
  @Nested() items?: MyItem[];
}

@ComponentBindings()
export class MyCollectionItem {
  @OneWay() text?: string;
}

@ComponentBindings()
export class MyItem extends MyCollectionItem {
  // no errors if there is 'MyItemOptionProps1' or 'MyItemOptionProps2' only
  @Nested() options?: MyItemOptionProps2 | MyItemOptionProps1; 
}

@ComponentBindings()
export class MyItemOptionProps1 {
  @OneWay() text1?: string;
}

@ComponentBindings()
export class MyItemOptionProps2 {
  @OneWay() text2?: string;
}
```

The console output:

```
c:\Work\GitHub\DevExtreme>npm run build:angular

> devextreme@21.2.0 build:angular c:\Work\GitHub\DevExtreme
> gulp generate-angular

Can not load ui.scheduler.timezones_data
[09:14:18] Using gulpfile c:\Work\GitHub\DevExtreme\gulpfile.js
[09:14:18] Starting 'generate-angular'...
[09:14:18] Starting 'cleanFrameworkArtifacts'...
[09:14:19] Finished 'cleanFrameworkArtifacts' after 701 ms
[09:14:19] Starting 'generate-angular-declaration-only'...
js\renovation\ui\toolbar\mycomponent.tsx(27,50): error TS2304: Cannot find name 'MyItemOptionProps1'.
js\renovation\ui\toolbar\mycomponent.tsx(31,39): error TS2304: Cannot find name 'MyItemOptionProps1'.
js\renovation\ui\toolbar\mycomponent.tsx(31,39): error TS4106: Parameter 'value' of accessor has or is using private name 'MyItemOptionProps1'.
js\renovation\ui\toolbar\mycomponent.tsx(35,45): error TS2304: Cannot find name 'MyItemOptionProps1'.
js\renovation\ui\toolbar\mycomponent.tsx(35,45): error TS4043: Return type of public getter 'options' from exported class has or is using private name 'MyItemOptionProps1'.
[09:14:53] 'generate-angular-declaration-only' errored after 34 s
[09:14:53] Error: js\renovation\ui\toolbar\mycomponent.tsx(27,50): error TS2304: Cannot find name 'MyItemOptionProps1'.
js\renovation\ui\toolbar\mycomponent.tsx(31,39): error TS2304: Cannot find name 'MyItemOptionProps1'.
js\renovation\ui\toolbar\mycomponent.tsx(31,39): error TS4106: Parameter 'value' of accessor has or is using private name 'MyItemOptionProps1'.
js\renovation\ui\toolbar\mycomponent.tsx(35,45): error TS2304: Cannot find name 'MyItemOptionProps1'.
js\renovation\ui\toolbar\mycomponent.tsx(35,45): error TS4043: Return type of public getter 'options' from exported class has or is using private name 'MyItemOptionProps1'.
    at formatError (c:\Work\GitHub\DevExtreme\node_modules\gulp\node_modules\gulp-cli\lib\versioned\^4.0.0\format-error.js:21:10)
    at Gulp.<anonymous> (c:\Work\GitHub\DevExtreme\node_modules\gulp\node_modules\gulp-cli\lib\versioned\^4.0.0\log\events.js:33:15)
    at Gulp.emit (events.js:327:22)
    at Gulp.EventEmitter.emit (domain.js:482:12)
    at Object.error (c:\Work\GitHub\DevExtreme\node_modules\undertaker\lib\helpers\createExtensions.js:61:10)
    at handler (c:\Work\GitHub\DevExtreme\node_modules\now-and-later\lib\mapSeries.js:47:14)
    at f (c:\Work\GitHub\DevExtreme\node_modules\once\once.js:25:25)
    at f (c:\Work\GitHub\DevExtreme\node_modules\once\once.js:25:25)
    at tryCatch (c:\Work\GitHub\DevExtreme\node_modules\async-done\index.js:24:15)
    at done (c:\Work\GitHub\DevExtreme\node_modules\async-done\index.js:40:12)
[09:14:53] 'generate-angular' errored after 35 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! devextreme@21.2.0 build:angular: `gulp generate-angular`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the devextreme@21.2.0 build:angular script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ignatov\AppData\Roaming\npm-cache\_logs\2021-07-07T06_14_53_237Z-debug.log
```
I have attached sources of my component and its props.
Error occurs when classes are declared in different files.
Compilation is successfully finished if all components are declared in one and the same file.

**Comment by IgnatovDan** [comment]
https://trello.com/c/R79eFkl7/2820-renovation-angular-cannot-use-few-complex-types-for-nested-component
[Teams - FYI The "error TS2304: Cannot find name 'MyItemOptionPro…](https://teams.microsoft.com/l/message/19:7f0f3823d62148e98d9f6bbf33128c0c@thread.skype/1625638910763?tenantId=e4d60396-9352-4ae8-b84c-e69244584fa4&groupId=8c31b3e5-5870-46b1-92a7-180d13b282ed&parentMessageId=1625638910763&teamName=DevExtreme&channelName=Renovation&createdTime=1625638910763)
